CREATE DATABASE QLNS;

GO
USE QLNS;

GO

SET DATEFORMAT DMY;

GO
CREATE TABLE CHITIETHOADON (
MAHOADON CHAR(7) NOT NULL,
MASACH CHAR(7),
SOLUONG INT,
GIATIEN INT,
THANHTIEN INT
);

GO
CREATE TABLE HOADON (
MAHOADON CHAR(7) PRIMARY KEY NOT NULL,
TENKHACHHANG NVARCHAR(50),
NGAYLAP DATETIME,
TONGTIEN DECIMAL(10, 2)
);

GO
CREATE TABLE KHO (
MASACH CHAR(7) PRIMARY KEY NOT NULL,
SOLUONG INT
);

GO
CREATE TABLE LINHVUC (
TENLINHVUC NVARCHAR(30) PRIMARY KEY NOT NULL
);

GO


CREATE TABLE LOAISACH (
TENLOAISACH NVARCHAR(30) PRIMARY KEY NOT NULL
);

GO
CREATE TABLE NHAXUATBAN (
TENNHAXUATBAN NVARCHAR(50) PRIMARY KEY NOT NULL
);

GO
CREATE TABLE SACH (
MASACH CHAR(7) PRIMARY KEY NOT NULL,
TENSACH NVARCHAR(100),
MATG CHAR(7) NOT NULL,
TENLINHVUC NVARCHAR(30),
TENLOAISACH NVARCHAR(30),
GIAMUA INT,
GIABIA INT,
LANTAIBAN INT,
TENNHAXUATBAN NVARCHAR(50),
NAMXUATBAN DATETIME
);

GO
CREATE TABLE TACGIA (
MATG CHAR(7) PRIMARY KEY NOT NULL,
TENTG NVARCHAR(40),
NAMSINH DATE,
NAMMAT DATE,
QUEQUAN NVARCHAR(20)
);

GO
CREATE TABLE TAIKHOAN (
USERNAME NVARCHAR(20) PRIMARY KEY NOT NULL,
PASS_WORD NVARCHAR(100) NOT NULL
);

GO
INSERT INTO TAIKHOAN (USERNAME, PASS_WORD)
VALUES ('admin', 'admin');

GO
CREATE PROC USP_Login
@username NVARCHAR(20), @password NVARCHAR(100)
AS
BEGIN
SELECT * FROM TAIKHOAN
WHERE USERNAME = @username AND PASS_WORD = @password
END;

GO
--Thêm khóa ngoại
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_CHITIETHOADON_HOADON
FOREIGN KEY (MAHOADON) REFERENCES HOADON(MAHOADON);

ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_CHITIETHOADON_SACH
FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);

ALTER TABLE KHO ADD CONSTRAINT FK_KHO_SACH
FOREIGN KEY (MASACH) REFERENCES SACH(MASACH);

ALTER TABLE SACH ADD CONSTRAINT FK_SACH_LOAISACH
FOREIGN KEY (TENLOAISACH) REFERENCES LOAISACH(TENLOAISACH);

ALTER TABLE SACH ADD CONSTRAINT FK_SACH_TACGIA
FOREIGN KEY (MATG) REFERENCES TACGIA(MATG);

ALTER TABLE SACH ADD CONSTRAINT FK_SACH_LINHVUC
FOREIGN KEY (TENLINHVUC) REFERENCES LINHVUC(TENLINHVUC);

ALTER TABLE SACH ADD CONSTRAINT FK_SACH_NHAXUATBAN
FOREIGN KEY (TENNHAXUATBAN) REFERENCES NHAXUATBAN(TENNHAXUATBAN);

GO
--Gọi Store Procedure đăng nhập
EXEC USP_Login @username = 'admin', @password = 'admin';